In [1]:
import pandas as pd

In [3]:
df=pd.read_excel("Sales Analysis Report.xlsx")

In [4]:
df

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Total Revenue
0,SO - 000225,2017-01-01,2017-01-13,28,Wholesale,NZD,AXW291,71,11,6,2499.1,1824.343,14994.6
1,SO - 0003378,2017-01-01,2017-01-06,7,Distributor,NZD,AXW291,54,7,11,2351.7,1269.918,25868.7
2,SO - 0003901,2017-01-01,2017-01-05,12,Wholesale,NZD,AXW291,58,13,5,1728.6,1019.874,8643.0
3,SO - 0005126,2017-01-01,2017-01-17,5,Wholesale,USD,AXW291,29,7,6,978.2,684.740,5869.2
4,SO - 0005614,2017-01-01,2017-01-07,27,Export,NZD,AXW291,31,6,7,2338.3,1028.852,16368.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0005237,2019-12-12,2019-12-16,41,Wholesale,NZD,FLR025,93,9,7,261.3,107.133,1829.1
7987,SO - 0005477,2019-12-12,2019-12-27,28,Distributor,AUD,FLR025,56,2,7,1996.6,1477.484,13976.2
7988,SO - 0006936,2019-12-12,2019-12-27,30,Wholesale,NZD,FLR025,66,1,9,3912.8,2817.216,35215.2
7989,SO - 0007126,2019-12-12,2019-12-25,6,Distributor,USD,FLR025,31,5,10,1855.9,1113.540,18559.0
7990,SO - 0007668,2019-12-12,2019-12-25,4,Wholesale,NZD,FLR025,65,13,11,3959.7,2138.238,43556.7

In [5]:
df.shape

(7991, 13)

In [6]:
df.head

<bound method NDFrame.head of        OrderNumber  OrderDate  Ship Date  Customer Name Index      Channel  \
0      SO - 000225 2017-01-01 2017-01-13                   28    Wholesale
1     SO - 0003378 2017-01-01 2017-01-06                    7  Distributor
2     SO - 0003901 2017-01-01 2017-01-05                   12    Wholesale
3     SO - 0005126 2017-01-01 2017-01-17                    5    Wholesale
4     SO - 0005614 2017-01-01 2017-01-07                   27       Export
...            ...        ...        ...                  ...          ...
7986  SO - 0005237 2019-12-12 2019-12-16                   41    Wholesale
7987  SO - 0005477 2019-12-12 2019-12-27                   28  Distributor
7988  SO - 0006936 2019-12-12 2019-12-27                   30    Wholesale
7989  SO - 0007126 2019-12-12 2019-12-25                    6  Distributor
7990  SO - 0007668 2019-12-12 2019-12-25                    4    Wholesale

     Currency Code Warehouse Code  Region Index  Product  Index  \
0              NZD         AXW291            71              11
1              NZD         AXW291            54               7
2              NZD         AXW291            58              13
3              USD         AXW291            29               7
4              NZD         AXW291            31               6
...            ...            ...           ...             ...
7986           NZD         FLR025            93               9
7987           AUD         FLR025            56               2
7988           NZD         FLR025            66               1
7989           USD         FLR025            31               5
7990           NZD         FLR025            65              13

      Order Quantity  Unit Price  Total Unit Cost  Total Revenue
0                  6      2499.1         1824.343        14994.6
1                 11      2351.7         1269.918        25868.7
2                  5      1728.6         1019.874         8643.0
3                  6       978.2          684.740         5869.2
4                  7      2338.3         1028.852        16368.1
...              ...         ...              ...            ...
7986               7       261.3          107.133         1829.1
7987               7      1996.6         1477.484        13976.2
7988               9      3912.8         2817.216        35215.2
7989              10      1855.9         1113.540        18559.0
7990              11      3959.7         2138.238        43556.7

[7991 rows x 13 columns]>

In [8]:
df.head()

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Total Revenue
0,SO - 000225,2017-01-01,2017-01-13,28,Wholesale,NZD,AXW291,71,11,6,2499.1,1824.343,14994.6
1,SO - 0003378,2017-01-01,2017-01-06,7,Distributor,NZD,AXW291,54,7,11,2351.7,1269.918,25868.7
2,SO - 0003901,2017-01-01,2017-01-05,12,Wholesale,NZD,AXW291,58,13,5,1728.6,1019.874,8643.0
3,SO - 0005126,2017-01-01,2017-01-17,5,Wholesale,USD,AXW291,29,7,6,978.2,684.740,5869.2
4,SO - 0005614,2017-01-01,2017-01-07,27,Export,NZD,AXW291,31,6,7,2338.3,1028.852,16368.1

In [9]:
df.tail()

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Total Revenue
7986,SO - 0005237,2019-12-12,2019-12-16,41,Wholesale,NZD,FLR025,93,9,7,261.3,107.133,1829.1
7987,SO - 0005477,2019-12-12,2019-12-27,28,Distributor,AUD,FLR025,56,2,7,1996.6,1477.484,13976.2
7988,SO - 0006936,2019-12-12,2019-12-27,30,Wholesale,NZD,FLR025,66,1,9,3912.8,2817.216,35215.2
7989,SO - 0007126,2019-12-12,2019-12-25,6,Distributor,USD,FLR025,31,5,10,1855.9,1113.540,18559.0
7990,SO - 0007668,2019-12-12,2019-12-25,4,Wholesale,NZD,FLR025,65,13,11,3959.7,2138.238,43556.7

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7991 entries, 0 to 7990
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OrderNumber          7991 non-null   object
 1   OrderDate            7991 non-null   datetime64[ns]
 2   Ship Date            7991 non-null   datetime64[ns]
 3   Customer Name Index  7991 non-null   int64
 4   Channel              7991 non-null   object
 5   Currency Code        7991 non-null   object
 6   Warehouse Code       7991 non-null   object
 7   Region Index         7991 non-null   int64
 8   Product  Index       7991 non-null   int64
 9   Order Quantity       7991 non-null   int64
 10  Unit Price           7991 non-null   float64
 11  Total Unit Cost      7991 non-null   float64
 12  Total Revenue        7991 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(4), object(4)
memory usage: 811.7+ KB

In [15]:
df.describe()

,OrderDate,Ship Date,Customer Name Index,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Total Revenue
count,7991,7991,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000,7991.000000
mean,2018-06-22 01:36:56.944061952,2018-07-02 12:04:35.710173952,25.457014,50.454261,6.340383,8.456889,2284.536504,1431.911054,19343.403904
min,2017-01-01 00:00:00,2017-01-05 00:00:00,1.000000,1.000000,1.000000,5.000000,167.500000,68.675000,837.500000
25%,2017-09-23 00:00:00,2017-10-03 00:00:00,13.000000,25.000000,2.000000,6.000000,1031.800000,606.115500,7959.600000
50%,2018-06-20 00:00:00,2018-07-01 00:00:00,25.000000,50.000000,7.000000,8.000000,1849.200000,1080.576000,13989.600000
75%,2019-03-20 00:00:00,2019-04-01 00:00:00,38.000000,76.000000,11.000000,10.000000,3611.300000,2040.250500,27436.500000
max,2019-12-12 00:00:00,2019-12-28 00:00:00,50.000000,100.000000,14.000000,12.000000,6566.000000,5498.556000,78711.600000
std,NaN,NaN,14.414883,28.862791,4.116455,2.283776,1673.096364,1112.413043,15586.133406

In [16]:
df.isnull()
#null value

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Total Revenue
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,False,False,False,False,False,False,False,False,False,False,False,False,False
7987,False,False,False,False,False,False,False,False,False,False,False,False,False
7988,False,False,False,False,False,False,False,False,False,False,False,False,False
7989,False,False,False,False,False,False,False,False,False,False,False,False,False
7990,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df.isnull().sum()

OrderNumber            0
OrderDate              0
Ship Date              0
Customer Name Index    0
Channel                0
Currency Code          0
Warehouse Code         0
Region Index           0
Product  Index         0
Order Quantity         0
Unit Price             0
Total Unit Cost        0
Total Revenue          0
dtype: int64

In [20]:
df.rename(columns={"Total Revenue" : "Revenue"},inplace=True)

In [19]:
df

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Total Revenue
0,SO - 000225,2017-01-01,2017-01-13,28,Wholesale,NZD,AXW291,71,11,6,2499.1,1824.343,14994.6
1,SO - 0003378,2017-01-01,2017-01-06,7,Distributor,NZD,AXW291,54,7,11,2351.7,1269.918,25868.7
2,SO - 0003901,2017-01-01,2017-01-05,12,Wholesale,NZD,AXW291,58,13,5,1728.6,1019.874,8643.0
3,SO - 0005126,2017-01-01,2017-01-17,5,Wholesale,USD,AXW291,29,7,6,978.2,684.740,5869.2
4,SO - 0005614,2017-01-01,2017-01-07,27,Export,NZD,AXW291,31,6,7,2338.3,1028.852,16368.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0005237,2019-12-12,2019-12-16,41,Wholesale,NZD,FLR025,93,9,7,261.3,107.133,1829.1
7987,SO - 0005477,2019-12-12,2019-12-27,28,Distributor,AUD,FLR025,56,2,7,1996.6,1477.484,13976.2
7988,SO - 0006936,2019-12-12,2019-12-27,30,Wholesale,NZD,FLR025,66,1,9,3912.8,2817.216,35215.2
7989,SO - 0007126,2019-12-12,2019-12-25,6,Distributor,USD,FLR025,31,5,10,1855.9,1113.540,18559.0
7990,SO - 0007668,2019-12-12,2019-12-25,4,Wholesale,NZD,FLR025,65,13,11,3959.7,2138.238,43556.7

In [21]:
df

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Total Unit Cost,Revenue
0,SO - 000225,2017-01-01,2017-01-13,28,Wholesale,NZD,AXW291,71,11,6,2499.1,1824.343,14994.6
1,SO - 0003378,2017-01-01,2017-01-06,7,Distributor,NZD,AXW291,54,7,11,2351.7,1269.918,25868.7
2,SO - 0003901,2017-01-01,2017-01-05,12,Wholesale,NZD,AXW291,58,13,5,1728.6,1019.874,8643.0
3,SO - 0005126,2017-01-01,2017-01-17,5,Wholesale,USD,AXW291,29,7,6,978.2,684.740,5869.2
4,SO - 0005614,2017-01-01,2017-01-07,27,Export,NZD,AXW291,31,6,7,2338.3,1028.852,16368.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0005237,2019-12-12,2019-12-16,41,Wholesale,NZD,FLR025,93,9,7,261.3,107.133,1829.1
7987,SO - 0005477,2019-12-12,2019-12-27,28,Distributor,AUD,FLR025,56,2,7,1996.6,1477.484,13976.2
7988,SO - 0006936,2019-12-12,2019-12-27,30,Wholesale,NZD,FLR025,66,1,9,3912.8,2817.216,35215.2
7989,SO - 0007126,2019-12-12,2019-12-25,6,Distributor,USD,FLR025,31,5,10,1855.9,1113.540,18559.0
7990,SO - 0007668,2019-12-12,2019-12-25,4,Wholesale,NZD,FLR025,65,13,11,3959.7,2138.238,43556.7

In [22]:
df.rename(columns={"Total Unit Cost" : "Unit Cost"},inplace=True)

In [23]:
df

,OrderNumber,OrderDate,Ship Date,Customer Name Index,Channel,Currency Code,Warehouse Code,Region Index,Product Index,Order Quantity,Unit Price,Unit Cost,Revenue
0,SO - 000225,2017-01-01,2017-01-13,28,Wholesale,NZD,AXW291,71,11,6,2499.1,1824.343,14994.6
1,SO - 0003378,2017-01-01,2017-01-06,7,Distributor,NZD,AXW291,54,7,11,2351.7,1269.918,25868.7
2,SO - 0003901,2017-01-01,2017-01-05,12,Wholesale,NZD,AXW291,58,13,5,1728.6,1019.874,8643.0
3,SO - 0005126,2017-01-01,2017-01-17,5,Wholesale,USD,AXW291,29,7,6,978.2,684.740,5869.2
4,SO - 0005614,2017-01-01,2017-01-07,27,Export,NZD,AXW291,31,6,7,2338.3,1028.852,16368.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0005237,2019-12-12,2019-12-16,41,Wholesale,NZD,FLR025,93,9,7,261.3,107.133,1829.1
7987,SO - 0005477,2019-12-12,2019-12-27,28,Distributor,AUD,FLR025,56,2,7,1996.6,1477.484,13976.2
7988,SO - 0006936,2019-12-12,2019-12-27,30,Wholesale,NZD,FLR025,66,1,9,3912.8,2817.216,35215.2
7989,SO - 0007126,2019-12-12,2019-12-25,6,Distributor,USD,FLR025,31,5,10,1855.9,1113.540,18559.0
7990,SO - 0007668,2019-12-12,2019-12-25,4,Wholesale,NZD,FLR025,65,13,11,3959.7,2138.238,43556.7

In [24]:
df["Revenue"].sum()

np.float64(154573140.60000002)

In [25]:
df["Revenue"].mean()

np.float64(19343.403904392446)

In [26]:
df["Revenue"].median()

13989.599999999999

In [27]:
df["Revenue"].max()

78711.6

In [28]:
df["Channel"].unquie()

AttributeError: 'Series' object has no attribute 'unquie'

In [29]:
df["Channel"].unique()

array(['Wholesale', 'Distributor', 'Export'], dtype=object)

In [30]:
df.groupby("Channel")["Revenue"].sum()

Channel
Distributor    48969690.3
Export         22636874.6
Wholesale      82966575.7
Name: Revenue, dtype: float64

In [32]:
df.groupby("Currency Code")["Unit Cost"].mean()

Currency Code
AUD    1471.124886
EUR    1467.680911
GBP    1433.190991
NZD    1417.057838
USD    1418.569455
Name: Unit Cost, dtype: float64