In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Anu", "Bala", "Charan", "Divya", None],
    "Age": [23, np.nan, 25, 22, 24],
    "Salary": [50000, 60000, np.nan, 45000, None]
}

df = pd.DataFrame(data)
print(df)

     Name   Age   Salary
0     Anu  23.0  50000.0
1    Bala   NaN  60000.0
2  Charan  25.0      NaN
3   Divya  22.0  45000.0
4    None  24.0      NaN

In [2]:
import pandas as pd
import numpy as np

# Dataset 1 (Employee details)
df1 = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["Anu", "Bala", None, "Divya"],
    "Age": [23, np.nan, 25, 22]
})

# Dataset 2 (Salary details)
df2 = pd.DataFrame({
    "EmpID": [1, 2, 3, 5],
    "Salary": [50000, 60000, np.nan, 70000]
})

print(df1)
print(df2)

   EmpID   Name   Age
0      1    Anu  23.0
1      2   Bala   NaN
2      3   None  25.0
3      4  Divya  22.0
   EmpID   Salary
0      1  50000.0
1      2  60000.0
2      3      NaN
3      5  70000.0

In [3]:
df.dropna()

    Name   Age   Salary
0    Anu  23.0  50000.0
3  Divya  22.0  45000.0

In [4]:
ddf

NameError: name 'ddf' is not defined

In [5]:
df

     Name   Age   Salary
0     Anu  23.0  50000.0
1    Bala   NaN  60000.0
2  Charan  25.0      NaN
3   Divya  22.0  45000.0
4    None  24.0      NaN

In [7]:
df.fillna(0)

     Name   Age   Salary
0     Anu  23.0  50000.0
1    Bala   0.0  60000.0
2  Charan  25.0      0.0
3   Divya  22.0  45000.0
4       0  24.0      0.0

In [8]:
df.fillna("unknown")

      Name      Age   Salary
0      Anu     23.0  50000.0
1     Bala  unknown  60000.0
2   Charan     25.0  unknown
3    Divya     22.0  45000.0
4  unknown     24.0  unknown

In [9]:
df

     Name   Age   Salary
0     Anu  23.0  50000.0
1    Bala   NaN  60000.0
2  Charan  25.0      NaN
3   Divya  22.0  45000.0
4    None  24.0      NaN

In [11]:
df["Name"].fillna("unknown",inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\2762224796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("unknown",inplace=True)

In [12]:
df

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala   NaN  60000.0
2   Charan  25.0      NaN
3    Divya  22.0  45000.0
4  unknown  24.0      NaN

In [13]:
df["Age"].fillna(24.0,inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\2331829400.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(24.0,inplace=True)

In [14]:
df

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala  24.0  60000.0
2   Charan  25.0      NaN
3    Divya  22.0  45000.0
4  unknown  24.0      NaN

In [17]:
df.ffill()

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala  24.0  60000.0
2   Charan  25.0  60000.0
3    Divya  22.0  45000.0
4  unknown  24.0  45000.0

In [16]:
df

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala  24.0  60000.0
2   Charan  25.0      NaN
3    Divya  22.0  45000.0
4  unknown  24.0      NaN

In [18]:
df.bfill()

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala  24.0  60000.0
2   Charan  25.0  45000.0
3    Divya  22.0  45000.0
4  unknown  24.0      NaN

In [20]:
df.fillna(method='bfill',inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\1626352436.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',inplace=True)

In [21]:
df

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala  24.0  60000.0
2   Charan  25.0  45000.0
3    Divya  22.0  45000.0
4  unknown  24.0      NaN

In [22]:
df.fillna(method='ffill',inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\4116506308.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',inplace=True)

In [23]:
df

      Name   Age   Salary
0      Anu  23.0  50000.0
1     Bala  24.0  60000.0
2   Charan  25.0  45000.0
3    Divya  22.0  45000.0
4  unknown  24.0  45000.0

In [24]:
import pandas as pd
import numpy as np

# Dataset 1 (Employee details)
df1 = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["Anu", "Bala", None, "Divya"],
    "Age": [23, np.nan, 25, 22]
})

# Dataset 2 (Salary details)
df2 = pd.DataFrame({
    "EmpID": [1, 2, 3, 5],
    "Salary": [50000, 60000, np.nan, 70000]
})

print(df1)
print(df2)

   EmpID   Name   Age
0      1    Anu  23.0
1      2   Bala   NaN
2      3   None  25.0
3      4  Divya  22.0
   EmpID   Salary
0      1  50000.0
1      2  60000.0
2      3      NaN
3      5  70000.0

In [27]:
df1["Name"].fillna("Unknown",inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\1435070067.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Name"].fillna("Unknown",inplace=True)

In [28]:
df1

   EmpID     Name   Age
0      1      Anu  23.0
1      2     Bala   NaN
2      3  Unknown  25.0
3      4    Divya  22.0

In [29]:
df1["Age"].fillna(df1["Age"].mean(),inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\2202119480.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Age"].fillna(df1["Age"].mean(),inplace=True)

In [30]:
df1

   EmpID     Name        Age
0      1      Anu  23.000000
1      2     Bala  23.333333
2      3  Unknown  25.000000
3      4    Divya  22.000000

In [31]:
df2

   EmpID   Salary
0      1  50000.0
1      2  60000.0
2      3      NaN
3      5  70000.0

In [33]:
df2["Salary"].fillna(df2["Salary"].mean(),inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_22672\934035211.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Salary"].fillna(df2["Salary"].mean(),inplace=True)

In [34]:
df2

   EmpID   Salary
0      1  50000.0
1      2  60000.0
2      3  60000.0
3      5  70000.0

In [35]:
merged_inner=pd.merge(df1,df2,on="EmpID",how="inner")

In [36]:
merged_inner

   EmpID     Name        Age   Salary
0      1      Anu  23.000000  50000.0
1      2     Bala  23.333333  60000.0
2      3  Unknown  25.000000  60000.0

In [37]:
print(df1)
print(df2)

   EmpID     Name        Age
0      1      Anu  23.000000
1      2     Bala  23.333333
2      3  Unknown  25.000000
3      4    Divya  22.000000
   EmpID   Salary
0      1  50000.0
1      2  60000.0
2      3  60000.0
3      5  70000.0

In [38]:
merged_left=pd.merge(df1,df2,on="EmpID",how="left")

In [39]:
merged_left

   EmpID     Name        Age   Salary
0      1      Anu  23.000000  50000.0
1      2     Bala  23.333333  60000.0
2      3  Unknown  25.000000  60000.0
3      4    Divya  22.000000      NaN

In [40]:
merged_right=pd.merge(df1,df2,on="EmpID",how="right")

In [41]:
merged_right

   EmpID     Name        Age   Salary
0      1      Anu  23.000000  50000.0
1      2     Bala  23.333333  60000.0
2      3  Unknown  25.000000  60000.0
3      5      NaN        NaN  70000.0

In [42]:
import pandas as pd
import numpy as np

# Employees Table
df1 = pd.DataFrame({
    "EmpID": [1, 2, 3, 4, 5],
    "Name": ["Anu", None, "Charan", "Divya", None],
    "Age": [23, 24, None, 22, 26],
    "Department": ["HR", "IT", "IT", None, "Finance"]
})

# Salaries Table
df2 = pd.DataFrame({
    "EmpID": [1, 2, 3, 6],
    "Salary": [50000, None, 55000, 70000],
    "Bonus": [5000, 6000, None, 8000]
})

In [43]:
df1

   EmpID    Name   Age Department
0      1     Anu  23.0         HR
1      2    None  24.0         IT
2      3  Charan   NaN         IT
3      4   Divya  22.0       None
4      5    None  26.0    Finance

In [45]:
df2

   EmpID   Salary   Bonus
0      1  50000.0  5000.0
1      2      NaN  6000.0
2      3  55000.0     NaN
3      6  70000.0  8000.0