In [1]:
import pandas as pd
import numpy as np

# Employees dataset (df1)
df1 = pd.DataFrame({
    'EmpID': [1, 2, 3, 4, 5],
    'Name': ['Anand', 'Raj', None, 'Kumar', None],
    'Age': [25, np.nan, 30, 28, np.nan],
    'Department': ['IT', 'HR', None, 'Finance', 'IT']
})

# Salary dataset (df2)
df2 = pd.DataFrame({
    'EmpID': [1, 2, 3, 6],
    'Salary': [50000, np.nan, 60000, 70000],
    'Bonus': [5000, None, None, 7000]
})

In [2]:
df1

   EmpID   Name   Age Department
0      1  Anand  25.0         IT
1      2    Raj   NaN         HR
2      3   None  30.0       None
3      4  Kumar  28.0    Finance
4      5   None   NaN         IT

In [3]:
df2

   EmpID   Salary   Bonus
0      1  50000.0  5000.0
1      2      NaN     NaN
2      3  60000.0     NaN
3      6  70000.0  7000.0

In [5]:
print(df1.dtypes)

EmpID           int64
Name           object
Age           float64
Department     object
dtype: object

print(df2.dtypes)

In [6]:
print(df2.dtypes)

EmpID       int64
Salary    float64
Bonus     float64
dtype: object

In [7]:
print(df1.isnull().sum())
print(df2.isnull().sum())

EmpID         0
Name          2
Age           2
Department    1
dtype: int64
EmpID     0
Salary    1
Bonus     2
dtype: int64

In [8]:
df1['Name'].fillna("Unknown")

0      Anand
1        Raj
2    Unknown
3      Kumar
4    Unknown
Name: Name, dtype: object

In [9]:
df1['Name'].fillna("Unknown",inplace =True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_20344\1885564314.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Name'].fillna("Unknown",inplace =True)

In [10]:
df1

   EmpID     Name   Age Department
0      1    Anand  25.0         IT
1      2      Raj   NaN         HR
2      3  Unknown  30.0       None
3      4    Kumar  28.0    Finance
4      5  Unknown   NaN         IT

In [11]:
df1["Department"].fillna("Not Assigned",inplace=True)

C:\Users\AnandRaj\AppData\Local\Temp\ipykernel_20344\1865929295.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Department"].fillna("Not Assigned",inplace=True)

In [12]:
df1

   EmpID     Name   Age    Department
0      1    Anand  25.0            IT
1      2      Raj   NaN            HR
2      3  Unknown  30.0  Not Assigned
3      4    Kumar  28.0       Finance
4      5  Unknown   NaN            IT

In [15]:
ml=pd.merge(df1,df2,on="EmpID",how='left')

In [17]:
ml

   EmpID     Name   Age    Department   Salary   Bonus
0      1    Anand  25.0            IT  50000.0  5000.0
1      2      Raj   NaN            HR      NaN     NaN
2      3  Unknown  30.0  Not Assigned  60000.0     NaN
3      4    Kumar  28.0       Finance      NaN     NaN
4      5  Unknown   NaN            IT      NaN     NaN